"""creat model article_tag and conection

Revision ID: 663874db22ce
Revises: 2306de59fd52
Create Date: 2023-03-10 18:53:05.440701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663874db22ce'
down_revision = '2306de59fd52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aricle_tag_association',
    sa.Column('aricle_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aricle_id'], ['article.id'], name=op.f('fk_aricle_tag_association_aricle_id_article')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_aricle_tag_association_tag_id_tag'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aricle_tag_association')
    # ### end Alembic commands ###
